### ISSUE TITLE
Experience using meta-flutter

### ISSUE THREAD

**Issue by LefixBlue** [sony/meta-flutter#27]
Hi, after long time I had the chance again to use your meta-flutter layer to build `wayland-client` and flutter-engine for a custom board based on iMX8M-Nano from Variscite. I would like to share my current experience.

- First I got an error from bitbake because `depot-tools` is hosted on 'main' branch instead of 'master' branch, so I had to specify the branch in the flutter-engine recipe file.

After fixing that, building the wayland-client as well as the flutter-engine against my custom board with Yocto/Bitbake was no problem.

Furthermore I've tried to cross build a flutter app with eLinux against the Yocto SDK for my custom board:

- I've added clang to my yocto SDK as you mentioned
- In elinux, I've patched the 'elinux_build_target.dart' to match my compiler triple (`aarch64-poky-linux` in my case)
- Then i've set the environment to my Yocto SDK: `. <PATH_TO_SDK>/environment-setup-aarch64-poky-linux`
- Then I triggered: `flutter-elinux build elinux --target-arch=arm64 --target-sysroot=<PATH_TO_SDK>/sysroots/aarch64-poky-linux -v`
- Build was successful, however it obviously didn't take the right `gen_snapshot` to produce the 'libapp.so' because running it on my target I got errors that the snapshots not match each other. I also tried to copy the `gen_snapshot` from flutter-engine build results to `${FLUTTER_SDK}/bin/cache/artifacts/engine/linux-arm64-release/clang_x64/gen_snapshot` but still the same.
- I've then used the `gen_snapshot` from yocto build results of flutter-engine to build 'libapp.so manually ~> Info taken from: https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-apps

That's how I got the flutter-app finally running on my custom board.

What still confuses me a bit, which `gen_snapshot` was used when building my app automated with the elinux cmd?
And how I could tell elinux to take the one I need?
Because then the cross build process would be really straight forward.

Any hint/help would be very useful.

Thank you.

Edited: I found my issue - I just needed to clean build the flutter-app once again after copy `gen_snapshot` to `${FLUTTER_SDK}/bin/cache/artifacts/engine/linux-arm64-release/clang_x64/gen_snapshot` as otherwise the 'libapp.so' will no be re-generated. I did not clear the folder `.dart_tool/flutter_build/`

**Comment by HidenoriMatsubayashi** [comment]
@LefixBlue 

First of all, thank you for your feedback.

> First I got an error from bitbake because depot-tools is hosted on 'main' branch instead of 'master' branch, so I had to specify the branch in the flutter-engine recipe file.

If you can, I hope your contributions (PRs).

**Comment by jwinarske** [comment]
@LefixBlue You might consider https://github.com/meta-flutter/meta-flutter
It includes all of the Open Source Linux embedders, and has multiple CI jobs with pre-built images available.  It's used in Automotive Grade Linux and hence has a long term support commitment.
