### ISSUE TITLE
Flutter with web server as backend

### ISSUE THREAD

**Issue by 79rpm** [sony/meta-flutter#37]
Hello,

This is more of a question. Is it possible to build this Flutter version with a web server as a backend? I couldn't find anything in the high-level documentation. I have read that Flutter can run with a node.js backend on a Linux platform, but I am not sure if this project can support it. I believe it should be just a matter of configuration.

Thank you for your help,

**Comment by HidenoriMatsubayashi** [comment]
I'm not sure your target platforms, but I guess you can use [flutter-elinux](https://github.com/sony/flutter-elinux) or original [flutter](https://github.com/flutter/flutter) as Flutter for Web.
