### ISSUE TITLE
arm 32 bit bitbake error with do_configure

### ISSUE THREAD

**Issue by camaronut** [sony/meta-flutter#54]
Hi there,

I attempted to build meta-flutter (flutter-wayland-client) for our imx6sx based device.  That chip is a 32 bit arm chip.  I noticed that in the flutter engine recipe it has:
```
GN_TARGET_ARCH = "arm64"
```
I wrote a .bbappend to change this to "arm".  Unfortunately there's still some tooling that's forcing 64 bit builds.  It appears in do_configure it's calling gclient and there's a DEPS or hook that's trying to download 64 bit toolchains.  My bitbake error:
```
ERROR: flutter-engine-1.0-r0 do_configure: Execution of '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/temp/run.do_configure.2866349' failed with exit code 1
ERROR: Logfile of failure stored in: /hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/temp/log.do_configure.2866349
Log data follows:
| DEBUG: Executing shell function do_configure
| ________ running 'python3 src/third_party/dart/tools/generate_package_config.py' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| generate_package_config.py called
| ________ running 'python3 src/tools/remove_stale_pyc_files.py src/tools' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| ________ running 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| ________ running 'python3 src/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| ________ running 'python3 src/flutter/tools/pub_get_offline.py' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| ________ running 'python3 src/flutter/tools/download_dart_sdk.py --fail-loudly' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| ________ running 'python3 src/flutter/tools/githooks/setup.py' in '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0'
| ERROR Unresolved dependencies.
| //:archives(//build/toolchain/linux:clang_arm)
|   needs //build/toolchain/linux:clang_arm()
| //:default(//build/toolchain/linux:clang_arm)
|   needs //build/toolchain/linux:clang_arm()
| //:dist(//build/toolchain/linux:clang_arm)
|   needs //build/toolchain/linux:clang_arm()
... <snip!>
| //third_party/zlib:zlib_x86_simd(//build/toolchain/linux:clang_arm)
|   needs //build/toolchain/linux:clang_arm()
| 
| GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
| Generating GN files in: out/linux_release_arm
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/temp/run.do_configure.2866349' failed with exit code 1
ERROR: Task (/hd/dunfell/sources/meta-flutter/recipes-graphics/flutter-engine/flutter-engine.bb:do_configure) failed with exit code '1'
```
It appears "install-sysroot.py" is getting --arch=arm64 specified.

Any ideas on how I can get gclient to specify "--arch=arm"?

Also, it looks like gclient deps fetching is ignoring the Yocto sysroot, is there a way around that?  Or is the only way to build flutter is to use the Google sanctioned sysroot?

I'm using the 'dunfell' branch of meta-flutter.

Thanks in advance for any help!
Chris

**Comment by HidenoriMatsubayashi** [comment]
First of all, we don't support armv7.

> Also, it looks like gclient deps fetching is ignoring the Yocto sysroot, is there a way around that? Or is the only way to build flutter is to use the Google sanctioned sysroot?

Not sure. I need to check how to build for armv7.

> I'm using the 'dunfell' branch of meta-flutter.

Please use release tag or latest version (main branch).

**Comment by HidenoriMatsubayashi** [comment]
If you want to add armv7 builds, we welcome all your contribution.

**Comment by camaronut** [comment]
Thanks for your response.  :)

I switched to the main branch, but it seems there is no more SRC_URI in the flutter-engine.bb recipe.  Now I'm getting the following bitbake error:
```
WARNING: flutter-engine-1.0-r0 do_populate_lic: Could not copy license file /hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter/LICENSE to /hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/license-destdir/flutter-engine/LICENSE: [Errno 2] No such file or directory: '/hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter/LICENSE'
ERROR: flutter-engine-1.0-r0 do_populate_lic: QA Issue: flutter-engine: LIC_FILES_CHKSUM points to an invalid file: /hd/dunfell/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/flutter-engine/1.0-r0/flutter-engine-1.0/flutter/LICENSE [license-checksum]
ERROR: flutter-engine-1.0-r0 do_populate_lic: Fatal QA errors found, failing task.
```
When I check the build directory it appears no source was downloaded, that seems to be why the license verification fails.

I have a limited amount of time on this "Flutter Evaluation" sprint, but I'll try to get armv7 to build in that time.
Thanks!
Chris

**Comment by HidenoriMatsubayashi** [comment]
> I have a limited amount of time on this "Flutter Evaluation" sprint, but I'll try to get armv7 to build in that time.

If it's possible, I recommend you to try arm64 at first to figure out how to build.

**Comment by pclass-sensonix** [comment]
@camaronut - were you able to enable armv7? I am trying to do the same thing - use meta-flutter for a sama5d27 32-bit arm chip.

**Comment by camaronut** [comment]
@pclass-sensonix @HidenoriMatsubayashi, for several reasons, we wound up going with https://github.com/meta-flutter/meta-flutter for our evaluation.  It also has some problems when building 32 bit arm packages (gen-snapshot), we are able to work around it by using a --no-use-integer-division flag.
The details are here:
https://github.com/meta-flutter/meta-flutter/issues/204
Thanks!
Chris

**Comment by pclass-sensonix** [comment]
Awesome I will give that a try. Thanks for the information.

**Comment by HidenoriMatsubayashi** [comment]
I'll close this issue. Thanks.
