### ISSUE TITLE
flutter-wayland-client-1.0-r0 do_fetch: Fetcher failure: Unable to find revision 8f2221fbef28b478debb78dd233f5250b220ca99 in branch master even from upstrea

### ISSUE THREAD

**Issue by WolsYang** [sony/meta-flutter#64]
Build Configuration:
DISTRO               = "fsl-imx-wayland"
DISTRO_VERSION       = "5.15-kirkstone"
meta-poky            = "HEAD:602922d492351ee747d2ff00f8ed5aab284a706b"

When I do` $ bitbake flutter-wayland-client`

I got this error, is any one know how to fix it?

`flutter-wayland-client-1.0-r0 do_fetch: Fetcher failure: Unable to find revision 8f2221fbef28b478debb78dd233f5250b220ca99 in branch master even from upstrea`

**Comment by HidenoriMatsubayashi** [comment]
Thanks. Fixed.
