### ISSUE TITLE
clean build warnings & error on tasks.inc

### ISSUE THREAD

**Issue by r10kindsofpeople** [sony/meta-flutter#69]
Context: I'm doing a fresh build based on README.md, and thought this may be helpful...on first build, I encountered multiple instances of:

**WARNING: <snip>/flutter-drm-eglstream-so.bb: do_configure:prepend += is not a recommended operator combination, please replace it.**

So I suggest that in recipes-graphics/flutter-embedded-linux/tasks.inc
do_configure:prepend[depends] **+**= "flutter-engine:do_populate_sysroot"
should be
do_configure:prepend[depends] = "flutter-engine:do_populate_sysroot"
Not sure if there should be an appended space separator, Yocto can be funny like that.

Also getting an error **ERROR: Nothing RPROVIDES 'weston-xwayland', and weston RPROVIDES weston-xwayland but was skipped: missing required distro feature 'pam'**.
**DISTRO_FEATURES:append = " pam"** to local.conf seems to have solved that, and it's busy building now.

Advise if this is helpful/not helpful and if there's a better way.

**Comment by HidenoriMatsubayashi** [comment]
Thanks. Can you please create a patch and send a pull request?
