### ISSUE TITLE
Syntax expires in DRM-GBM backend conf/local.conf 

### ISSUE THREAD

**Issue by hizzd** [sony/meta-flutter#82]
Follow the tutorial in the README file to add conf/locale.conf line, An error has occurred:

`ERROR: Variable DISTRO_FEATURES_append file: /root/build/conf/local.conf line: 278 contains an operation using the old override syntax. Please convert this layer/metadata before attempting to use with a newer bitbake.`

After changing to `DISTRO_FEATURES:append = " systemd"`, WORK!

Related links：
https://low-level.wiki/yocto/honister-upgrade.html

**Comment by HidenoriMatsubayashi** [comment]
Thank you for reporting the issue.
